### ISSUE TITLE
Could you please provide data for your example

### ISSUE THREAD

**Issue by xuzhang5788** [TavoGLC/DataAnalysisByExample#1]
Thank you so much for your great repo. It will be great if you would like to provide datasets for your examples. Great work!

**Comment by TavoGLC** [comment]
Sorry for the delay, Ido not have a stable internet connection and upload these examples every few weeks. Most of the links are in my medium blog. However, if for whatever reason I didn't include the link here are some of the links:

https://www.kaggle.com/blastchar/telco-customer-churn
https://www.kaggle.com/currie32/crimes-in-chicago
https://www.kaggle.com/insiyeah/musicfeatures

I have also used the MINST data set for one example. And others were from private consulting and I was not allowed to disclose the data. Thank you for making me notice that I can be also contacted through this media.
